// End-to-end test of the cross-issuer wrap path: a Pixel-Camera-captured
// JPEG (parent ingredient, signed by Google's Pixel C2PA root) wrapped
// in a RealReel Stage 2 manifest (active, signed by the user's
// RealReel-enrolled hardware key).
//
// Fixture: __tests__/fixtures/pixel-uploaded.jpg — generated by
// uploading a Pixel-Camera photo through the local dev pipeline with
// the wrap-mode profile enabled. Pull from local Supabase storage with:
//
//   supabase storage cp \
//     "ss:///media/<your-user-id>/<timestamp>.jpg" \
//     verifier/__tests__/fixtures/pixel-uploaded.jpg \
//     --local --experimental
//
// The describe.skipIf() below makes this suite a no-op until the fixture
// lands, so the file is safe to commit independently.
//
// What this suite uniquely covers (vs verify-realreel.test.ts, which
// exercises native two-stage):
//   1. Force-wrap: active manifest's issuer is "RealReel" → it passes the
//      force-wrap gate and runs the realreel profile (the single ingestion
//      profile). A Pixel parent under a RealReel Stage 2 is accepted.
//   2. The Pixel parent is validated by c2pa-node's chain check + the
//      issuer-agnostic Stage-1 structural rules; no separate wrap branch.
//   3. Stage 1 cert IS looked up now — but only for the revocation denylist.
//      In wrap mode the Pixel parent was never enrolled, so
//      that lookup returns null and is skipped; the capturer's user_id is
//      never bound (cross-user preserved). lookupSigningKeyRevocation is
//      called for both stages.
//   4. Stage 2 still runs full validation (cert lookup, revocation,
//      attestation in lenient mode). The user_id == JWT binding was dropped
//      — the verifier is user-anonymous.
//   5. Sanitized output carries both manifests; trust_source = "realreel";
//      parent_label resolves to the Pixel-signed Stage 1 manifest.
//
// Stage-2 rejection paths in wrap mode: the second describe.skipIf
// block below pins KEY_NOT_FOUND and KEY_REVOKED on the wrap path. They
// share the same code path as native two-stage today (Stage 2 lookup is
// the same), so the cases are short — but explicit coverage guards against
// a future refactor that could subtly diverge the wrap branch (e.g. by
// hoisting Stage 1 + Stage 2 lookups into different helpers).

import { describe, it, expect, vi, beforeEach } from "vitest";
import { readFile, access } from "node:fs/promises";
import { resolve } from "node:path";

// Mock the db module BEFORE importing modules that depend on it.
//
// Two DB-touching primitives matter on the wrap path:
//   - lookupSigningKeyRevocation: Stage 2 cert lookup.
//   - consumeAndRecordAttestation: Stage 2 attestation nonce burn,
//     called from both attestation/apple.ts and attestation/play_integrity.ts.
//     The Stage-2 wrap on modern builds carries an org.realreel.app_attest
//     (iOS) or org.realreel.play_integrity (Android) assertion that
//     reaches consume; we no-op it here so the test asserts dispatch
//     behavior rather than nonce-tracking semantics (those are covered
//     by attestation-apple.test.ts + attestation-play-integrity.test.ts).
vi.mock("../src/db.js", () => {
  const lookupSigningKeyRevocation = vi.fn();
  const consumeAndRecordAttestation = vi.fn().mockResolvedValue(undefined);
  const pingDb = vi.fn();
  return {
    lookupSigningKeyRevocation,
    consumeAndRecordAttestation,
    pingDb,
    initDb: vi.fn(),
    closeDbPool: vi.fn(),
    // The default VerifierDatastore the profile / attestation consumers fall
    // back to when no adapter is injected. Delegates to the same spies so the
    // existing `vi.mocked(lookupSigningKeyRevocation)` assertions stay valid.
    postgresAdapter: {
      lookup: lookupSigningKeyRevocation,
      burn: consumeAndRecordAttestation,
      ping: pingDb,
    },
  };
});

import { verify } from "../src/verify.js";
import { loadTrustConfig } from "../src/trust/loader.js";
import { lookupSigningKeyRevocation } from "../src/db.js";
import { VerifyErrorCode } from "../src/errors.js";

const wrapFixturePath = resolve(
  import.meta.dirname,
  "fixtures/pixel-uploaded.jpg",
);
const trustSourcesPath = resolve(import.meta.dirname, "../trust-sources.yaml");

// Skip the whole suite if the fixture doesn't exist yet. Lets this file
// land in the repo before the fixture is generated and pulled into
// place — and CI won't fail on the missing JPEG.
const fixtureExists = await access(wrapFixturePath)
  .then(() => true)
  .catch(() => false);

// Mock Stage 2 user_id. The cert lookup is mocked and the verifier no
// longer binds user_id, so any UUID works.
const STAGE2_USER = "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa";

// The wrap fixture's two leaf serials, read from pixel-uploaded.jpg:
//   - Stage 1 (parent) is Pixel-signed (issuer "Google LLC") and was never
//     enrolled in user_signing_keys → the revocation lookup returns null.
//   - Stage 2 (active) is the uploader's RealReel-enrolled key.
const WRAP_STAGE2_SERIAL = "366034370023378372163055906556400858549271388429";
const WRAP_STAGE1_SERIAL = "1895194320007564465405856282168006996785831173";

// Default mocked Stage-2 revocation row. The wrap fixture was produced
// on Android (Pixel device running the RealReel app), so the
// signing-key platform is one of the Android variants. The exact
// variant ('android-strongbox' vs 'android-tee') doesn't affect the
// dispatch logic exercised by these tests — both route Play Integrity
// envelopes the same way.
function defaultStage2Row(opts: { userId?: string; revoked?: boolean } = {}) {
  return {
    key_id: "stage2-mocked-key-id",
    user_id: opts.userId ?? STAGE2_USER,
    revoked_at: opts.revoked ? "2026-05-28T12:00:00.000Z" : null,
    cert_serial_number: WRAP_STAGE2_SERIAL,
    platform: "android-strongbox",
    public_key: Buffer.alloc(0),
    app_attest_public_key: null,
  };
}

// Input-aware mock modelling production: ONLY the RealReel Stage-2 key is
// enrolled. The Pixel Stage-1 parent isn't, so its revocation lookup
// returns null and the denylist skips it. Order-independent.
// Pass null to also make the Stage-2 lookup miss (KEY_NOT_FOUND path).
function mockWrapKeys(stage2Row: ReturnType<typeof defaultStage2Row> | null): void {
  vi.mocked(lookupSigningKeyRevocation).mockImplementation(async (serial: string) =>
    serial === WRAP_STAGE2_SERIAL ? stage2Row : null,
  );
}

describe.skipIf(!fixtureExists)(
  "verify() — Pixel parent + RealReel Stage 2 wrap",
  () => {
    let wrapBytes: Buffer;
    let trustConfig: Awaited<ReturnType<typeof loadTrustConfig>>;

    beforeEach(async () => {
      vi.mocked(lookupSigningKeyRevocation).mockReset();
      wrapBytes = await readFile(wrapFixturePath);
      trustConfig = await loadTrustConfig(trustSourcesPath);
    });

    it("happy path: accepts the wrap; trust_source='realreel'; parent_label populated", async () => {
      mockWrapKeys(defaultStage2Row());

      const result = await verify({
        assetBytes: wrapBytes,
        mimeType: "image/jpeg",
        expectedUserId: STAGE2_USER,
        trustConfig,
        declaredLocation: "precise",
      });

      // Active manifest is RealReel-signed → dispatcher routes to the
      // realreel profile, sanitize stamps trust_source accordingly.
      expect(result.sanitizedManifest.trust_source).toBe("realreel");
      expect(result.sanitizedManifest.validation_state).toBe("trusted");
      // parent_label is the load-bearing signal that the wrap structure
      // survived sanitization — the parent (Pixel) manifest is still in
      // the store, addressable by label.
      expect(result.sanitizedManifest.active_manifest).not.toBeNull();
      expect(result.sanitizedManifest.active_manifest?.parent_label).toBeTruthy();
    });

    it("wrap-mode behavior: BOTH stages are looked up; the Pixel Stage-1 parent misses the registry (denylist skip)", async () => {
      mockWrapKeys(defaultStage2Row());

      await verify({
        assetBytes: wrapBytes,
        mimeType: "image/jpeg",
        expectedUserId: STAGE2_USER,
        trustConfig,
        declaredLocation: "precise",
      });

      // Dual-stage revocation: both the Stage-1 (Pixel) and
      // Stage-2 (RealReel) serials are looked up. The Pixel parent was
      // never enrolled, so its lookup returns null and the denylist skips
      // it — which is exactly why the Stage-1 denylist only bites native
      // RealReel captures. Assert both serials hit the lookup and the Pixel
      // serial resolved to null (not enrolled).
      expect(vi.mocked(lookupSigningKeyRevocation)).toHaveBeenCalledTimes(2);
      expect(vi.mocked(lookupSigningKeyRevocation)).toHaveBeenCalledWith(WRAP_STAGE1_SERIAL);
      expect(vi.mocked(lookupSigningKeyRevocation)).toHaveBeenCalledWith(WRAP_STAGE2_SERIAL);
    });

    it("parent ingredient is Pixel-signed (issuer contains 'Google LLC')", async () => {
      mockWrapKeys(defaultStage2Row());

      const result = await verify({
        assetBytes: wrapBytes,
        mimeType: "image/jpeg",
        expectedUserId: STAGE2_USER,
        trustConfig,
        declaredLocation: "precise",
      });

      const parentLabel = result.sanitizedManifest.active_manifest!.parent_label!;
      const parent = result.sanitizedManifest.manifests[parentLabel];
      expect(parent).toBeDefined();
      // Empirically pinned against TRUSTED_ISSUERS[id=pixel].issuerMatch.
      // The dispatcher tightening additionally requires
      // common_name === "Pixel Camera" before routing here; that check
      // happens upstream (verifier/src/trust/dispatcher.ts) on the raw
      // c2pa-node manifest — see trust-source-dispatch.test.ts for the
      // common_name routing regression coverage. The SanitizedManifest now
      // persists that common_name too, so a viewer can name the camera.
      expect(parent.signature_info.issuer).toContain("Google LLC");
      expect(parent.signature_info.common_name).toBe("Pixel Camera");
    });

    it("drops the Pixel parent's hash bindings + the upload attestation envelope", async () => {
      mockWrapKeys(defaultStage2Row());

      const result = await verify({
        assetBytes: wrapBytes,
        mimeType: "image/jpeg",
        expectedUserId: STAGE2_USER,
        trustConfig,
        declaredLocation: "precise",
      });

      const labels = Object.values(result.sanitizedManifest.manifests).flatMap(
        (m) => m.assertions.map((a) => a.label),
      );
      // The Pixel Stage-1 carries c2pa.hash.* hard-bindings (the bulk of a
      // wrap manifest) and the RealReel Stage-2 carries the attestation
      // envelope — both re-verification-only, both stripped.
      expect(labels.some((l) => l.startsWith("c2pa.hash."))).toBe(false);
      expect(labels).not.toContain("org.realreel.play_integrity");
      // The signed EXIF survives for the viewer.
      expect(labels).toContain("stds.exif");
      // Real-row size pin (unfiltered this wrap is ~6.4 KB).
      expect(JSON.stringify(result.sanitizedManifest).length).toBeLessThan(5000);
    });
  },
);

// ---------------------------------------------------------------
// Stage-2 rejection paths in wrap mode
// ---------------------------------------------------------------
//
// These mirror the native-mode Stage 2 rejections covered in
// verify-realreel.test.ts but pin them in wrap mode explicitly. The
// code path is shared today (Stage 2 lookup → revocation check → throw on
// failure); these tests guard against a future divergence where wrap-mode
// subtly skipped or reordered the check.
//
// Out of scope for this block: the "disallowed Stage 2 action on wrap"
// case. Synthesizing it would require either (a) a fixture whose Stage
// 2 carries a non-allowlisted action — not derivable from the canonical
// pixel-uploaded.jpg without re-signing the manifest, or (b) invasive
// mocking of c2pa-rs's Reader to swap assertions, which couples the
// test to the binding's internals. The wrap-parent action-allowlist
// logic itself is covered by verify-pixel.test.ts + policy.test.ts
// (synthetic ManifestStoreShape) for native parents; the wrap-mode
// branch enforces the SAME allowlist by construction (same helper,
// no wrap-specific bypass).

describe.skipIf(!fixtureExists)(
  "verify() — wrap mode Stage-2 rejections",
  () => {
    let wrapBytes: Buffer;
    let trustConfig: Awaited<ReturnType<typeof loadTrustConfig>>;

    beforeEach(async () => {
      vi.mocked(lookupSigningKeyRevocation).mockReset();
      wrapBytes = await readFile(wrapFixturePath);
      trustConfig = await loadTrustConfig(trustSourcesPath);
    });

    it("rejects with KEY_NOT_FOUND when Stage 2's cert serial isn't enrolled", async () => {
      // Nothing enrolled → every lookup misses. Stage 1 (Pixel) misses and
      // the denylist skips it; Stage 2 misses and maps to KEY_NOT_FOUND.
      mockWrapKeys(null);

      await expect(
        verify({
          assetBytes: wrapBytes,
          mimeType: "image/jpeg",
          expectedUserId: STAGE2_USER,
          trustConfig,
          declaredLocation: "precise",
        }),
      ).rejects.toMatchObject({ code: VerifyErrorCode.KEY_NOT_FOUND });

      // Both stages are consulted now (Stage 1 for the denylist, Stage 2 for
      // the gate); the Pixel Stage-1 miss is a skip, the Stage-2 miss throws.
      expect(vi.mocked(lookupSigningKeyRevocation)).toHaveBeenCalledTimes(2);
    });

    it("rejects with KEY_REVOKED when Stage 2's cert is revoked", async () => {
      // The enrolled RealReel Stage-2 key is revoked; the Pixel Stage-1
      // parent is (as always) not enrolled, so it's skipped.
      mockWrapKeys(defaultStage2Row({ revoked: true }));

      await expect(
        verify({
          assetBytes: wrapBytes,
          mimeType: "image/jpeg",
          expectedUserId: STAGE2_USER,
          trustConfig,
          declaredLocation: "precise",
        }),
      ).rejects.toMatchObject({ code: VerifyErrorCode.KEY_REVOKED });

      expect(vi.mocked(lookupSigningKeyRevocation)).toHaveBeenCalledTimes(2);
    });

    it("accepts when Stage 2's key belongs to a different user_id (verifier is user-anonymous)", async () => {
      // The user_id == JWT binding was dropped. A Stage 2 key
      // whose recorded owner differs from expectedUserId is accepted — the
      // previous UNTRUSTED_ISSUER rejection no longer fires.
      mockWrapKeys(defaultStage2Row({ userId: "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb" }));

      const result = await verify({
        assetBytes: wrapBytes,
        mimeType: "image/jpeg",
        expectedUserId: STAGE2_USER, // differs from the row's user_id
        trustConfig,
        declaredLocation: "precise",
      });
      expect(result.sanitizedManifest.validation_state).toBe("trusted");
    });
  },
);
